### ISSUE TITLE
Styling Switches not working

### ISSUE THREAD

**Issue by lordzouga** [drewjbartlett/vue-switches#14]
Hello,

Thanks for making this component.

I am trying to style the switch using css. Below is my selector:
```css
.parent .vue-switcher.vue-switcher-theme--bulma.vue-switcher-color--blue div{
        background-color: rgba(102, 0, 204, 0.685);
    }

.parent .vue-switcher.vue-switcher-theme--bulma.vue-switcher-color--blue div:after {
      background-color: #6600CC;
}
```
the style gets ignored during render. 

Any form of help is welcome. Thanks
